# Install wordpress on Amazon Linux based machines
- hosts: aml_instances
  become: yes
  vars_files:
    - packages.yml
  
  tasks: 
  - name: Install apache server 
    ansible.builtin.dnf:
      name: httpd
      state: latest

  - name: Start apache service, if not started and make it permanent
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes 

  - name: Install other packages needed for wordpress
    ansible.builtin.dnf:
      name: "{{ wordpress.aml_packages }}"
      state: latest
    ignore_errors: yes

  - name: Download latest WordPress files
    ansible.builtin.get_url:
      url: "https://wordpress.org/latest.tar.gz"
      dest: "/tmp/latest.tar.gz"
  
  - name: Extract WordPress from archive and give needed permissions and ownership
    ansible.builtin.unarchive:
      src: "/tmp/latest.tar.gz"
      dest: "/tmp/"
      remote_src: yes

  - name: Check if wordpress files already in folder
    ansible.builtin.stat:
      path: /var/www/html/wp-settings.php
    register: does_wordpress

  # Only continue if there are no pre-installed wordpress files in a folder  
  - block:
    - name: Copy from WordPress folder to /var/www/html/
      ansible.builtin.copy:
        src: /tmp/wordpress/
        dest: /var/www/html/
        remote_src: yes

    - name: Change ownership and permissions of all files in a folder with wordpress
      ansible.builtin.file:
        path: /var/www/html
        owner: apache
        group: apache
        mode: "0755"
        recurse: yes

    - name: Delete wordpress tmp folder
      ansible.builtin.file:
        path: /tmp/wordpress/
        state: absent
    
    - name: Delete wordpress archive file
      ansible.builtin.file:
        path: /tmp/latest.tar.gz
        state: absent
    when: does_wordpress.stat.exists == false

  - name: Restart Apache service
    ansible.builtin.service:
      name: httpd
      state: restarted
